version: "3.9"

services:
  database:
    container_name: "rates-database"
    build:
      context: ./deployment/database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ratestask
